### ISSUE TITLE
adaptive_grain uses get_neutral_value incorrectly 

### ISSUE THREAD

**Issue by yuv420p10le** [Vodes/vodesfunc#17]
Broke with this commit of vstools: https://github.com/Jaded-Encoding-Thaumaturgy/vs-tools/commit/f75b250def4b34e69cafb86d0ba3364fe2939607

```
  File "vodesfunc/noise.py", line 88, in adaptive_grain
    neutral = [get_neutral_value(clip), get_neutral_value(clip, True)]
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_neutral_value() takes 1 positional argument but 2 were given
```

**Comment by Vodes** [comment]
Semi aware of it but I won't be home for roughly a week and don't even have my setup updated. PR appreciated, can still merge anytime
